# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main cmd/internal/main.go"  # 编译命令
  include_ext = ["go", "tpl", "tmpl", "html"]  # 监控的文件扩展名
  exclude_dir = ["web", "vue-vben-admin"]  # 排除的目录

[run]
  cmd = "go run cmd/internal/main.go"  # 运行命令

[log]
  level = "info"
